from pathlib import Path

DEFAULT_DATA_DIR = Path.home() / ".tgvectordb"
DEFAULT_MODEL_NAME = "intfloat/e5-small-v2"
DEFAULT_DIMENSIONS = 384
TELEGRAM_MSG_CHAR_LIMIT = 4096
MAX_TEXT_CHUNK_CHARS = 2800
TG_FETCH_BATCH_SIZE = 100
TG_SEND_DELAY = 1
TG_SEND_BURST_SIZE = 15
TG_SEND_BURST_PAUSE = 5
CLUSTERING_THRESHOLD = 1000
MIN_CLUSTERS = 8
MAX_CLUSTERS = 128
REINDEX_GROWTH_TRIGGER = 0.10
DEFAULT_NPROBE = 3
CHANNEL_OVERFLOW_THRESHOLD = 700_000
DEFAULT_CACHE_MAX_ITEMS = 50_000
CHANNEL_PREFIX = "tgvdb"
